server:
  port: 8048

app:
  topic-name: xmfueozy-my-kafka-topic
  group-id: xmfueozy-consumers

spring:
  kafka:
    bootstrap-servers: dory.srvs.cloudkafka.com:9094
    properties:
      security.protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="xmfueozy" password="2XI0FnNCpKFOeNL5Mf7_CtbkhQIkxrpB";

    consumer:
      group-id: xmfueozy-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: com.example.kafkatest
#    dead_letter_topic: retry_topic

