server.port: 8047

app:
  topic-name: my-local-topic


spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer




# program argument for local profile
# --spring.profiles.active=local